### ISSUE TITLE
IOMesh can support data sharding ?

### ISSUE THREAD

**Issue by tomsunyu** [iomesh/charts#28]
IOMesh can support data sharding ?

**Comment by kylezh** [comment]
Hi @tomsunyu, thanks for your question.

What do you mean by 'data sharding'?
IOMesh is a distributed storage. And data is distributed among all nodes.

**Comment by tomsunyu** [comment]
In short, the data sharding function can split the data into multiple objects and store them in different nodes.

**Comment by kylezh** [comment]
> In short, the data sharding function can split the data into multiple objects and store them in different nodes.

IOMesh works in the same way as you described.
